### ISSUE TITLE
NorthwindPhoto: Need to check RadialController.IsSupported() before calling RadialController.CreateForCurrentView()

### ISSUE THREAD

**Issue by paulmon** [Microsoft/uwp-experiences#31]
If RadialController.CreateForCurrentView() is called on a Windows edition that doesn't support the dial control it throws an exception.  The code should check RadialController.IsSupported() before calling RadialController.CreateForCurrentView() so that it will work on all platforms that support UWP.  Windows IoT Core for example.

**Comment by shenchauhan** [comment]
Please submit a PR for this. I'll review and merge.
