### ISSUE TITLE
When add Kinect support?

### ISSUE THREAD

**Issue by LGinC** [Microsoft/uwp-experiences#39]
I want to use Kinect v2 in my UWP app?
but Kinect SDK just support dotnet framework 4.5

**Comment by nmetulev** [comment]
Check out [this blog](https://blogs.msdn.microsoft.com/kinectforwindows/2016/05/13/kinect-and-uwp-new-options-in-the-windows-10-anniversary-update/) post that discusses how to access Kinect data in UWP
