### ISSUE TITLE
Null reference exception in HandleIntent(string text)

### ISSUE THREAD

**Issue by mcorning** [Microsoft/uwp-experiences#8]
**Unexpected Result**
Here is the top of the stack when the exception is thrown (text argument reads "who is closest"):
   
at Microsoft.Cognitive.LUIS.Intent.Load(JObject intent)
   at Microsoft.Cognitive.LUIS.LuisResult.Load(JToken result)
   at Microsoft.Cognitive.LUIS.LuisResult..ctor(LuisClient client, JToken result)
   at Microsoft.Cognitive.LUIS.LuisClient.<Predict>d__19.MoveNext()

**Steps Taken**
- Double checked that the LUIS configuration properties were correct (so we'll need to add additional text to her suggestion when an exception occurs based on what we discover here)
- I tried speaking, "Show me photos from shen" and got the same exception 
- Added an utterance to the LUIS model, and it came back with the correct Intent.  

so flying blind here, I'm not sure what to do next. I don't suppose we can debug into LUIS...

**Be Advised**
oh, and for anybody coming later, if you want to debug AdventureWorks (and not feel like you're losing your mind), be sure to uncheck "Optimize code" in the (Project) Build properties.

**Comment by mcorning** [comment]
**RESOLVED**
The Setup Steps fail to note that after you import the .json, you need to Publish the model. Publishing is also the best way to test your model because adding your text to the query on the Publish page actually calls the model the way this app will.

**Comment by nmetulev** [comment]
Hey @mcorning, this is great feedback, I updated the readme to add a note on publishing the model. Note that the original branch for the app is now deprecated and it's been moved to the master branch: https://github.com/Microsoft/uwp-experiences/tree/master/apps/social
